language: csharp
sudo: required
dist: xenial
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
mono: none
branches:
  only:
    - master
script:
  - ./build/get-dotnet.sh
  - ./build_and_test.sh
