language: csharp
sudo: required
dist: xenial
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
mono: none
branches:
  only:
    - master
install:
  - ./build/get-dotnet.sh
  - export PATH="~/.dotnet/:$PATH"
script:
  - ./build_and_test.sh
