<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <MicrosoftAspNetCoreAppPackageVersion>10.0.11</MicrosoftAspNetCoreAppPackageVersion>
    <MicrosoftAspNetCoreApp9PackageVersion>9.0.19</MicrosoftAspNetCoreApp9PackageVersion>
    <MicrosoftAspNetCoreApp8PackageVersion>8.0.30</MicrosoftAspNetCoreApp8PackageVersion>
    <GrpcDotNetPackageVersion>2.83.0</GrpcDotNetPackageVersion>
    <OpenTelemetryPackageVersion>1.15.3</OpenTelemetryPackageVersion>
    <OpenTelemetryAspNetCoreInstrumentationPackageVersion>1.15.2</OpenTelemetryAspNetCoreInstrumentationPackageVersion>
    <OpenTelemetryHttpInstrumentationPackageVersion>1.15.1</OpenTelemetryHttpInstrumentationPackageVersion>
    <OpenTelemetryGrpcPackageVersion>1.15.1-beta.1</OpenTelemetryGrpcPackageVersion>
    <MicrosoftExtensionsPackageVersion>10.0.11</MicrosoftExtensionsPackageVersion>
    <MicrosoftExtensionsLtsPackageVersion>8.0.1</MicrosoftExtensionsLtsPackageVersion>
  </PropertyGroup>
  <ItemGroup>
    <!-- ASP.NET Core -->
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly" Version="$(MicrosoftAspNetCoreAppPackageVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="$(MicrosoftAspNetCoreAppPackageVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="$(MicrosoftAspNetCoreAppPackageVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.Certificate" Version="$(MicrosoftAspNetCoreAppPackageVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="$(MicrosoftAspNetCoreAppPackageVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.TestHost" Version="$(MicrosoftAspNetCoreAppPackageVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="$(MicrosoftAspNetCoreAppPackageVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Grpc.JsonTranscoding" Version="$(MicrosoftAspNetCoreAppPackageVersion)" />

    <!-- Extensions -->
    <PackageVersion Include="Microsoft.Extensions.Http" Version="$(MicrosoftExtensionsPackageVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="$(MicrosoftExtensionsPackageVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="$(MicrosoftExtensionsPackageVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="$(MicrosoftExtensionsPackageVersion)" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="$(MicrosoftExtensionsPackageVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="$(MicrosoftExtensionsPackageVersion)" />

    <!-- gRPC -->
    <PackageVersion Include="Grpc.Tools" Version="2.83.0" />
    <PackageVersion Include="Grpc.Core" Version="2.46.6" />
    <PackageVersion Include="Grpc.Core.Api" Version="$(GrpcDotNetPackageVersion)"/>
    <PackageVersion Include="Grpc.Net.Client" Version="$(GrpcDotNetPackageVersion)" />
    <PackageVersion Include="Grpc.Net.Client.Web" Version="$(GrpcDotNetPackageVersion)" />
    <PackageVersion Include="Grpc.Net.ClientFactory" Version="$(GrpcDotNetPackageVersion)" />
    <PackageVersion Include="Grpc.AspNetCore" Version="$(GrpcDotNetPackageVersion)" />
    <PackageVersion Include="Grpc.AspNetCore.Server" Version="$(GrpcDotNetPackageVersion)" />
    <PackageVersion Include="Grpc.AspNetCore.Web" Version="$(GrpcDotNetPackageVersion)" />
    <PackageVersion Include="Grpc.Reflection" Version="$(GrpcDotNetPackageVersion)" />
    <PackageVersion Include="Grpc.AspNetCore.Server.Reflection" Version="$(GrpcDotNetPackageVersion)" />
    <PackageVersion Include="Grpc.HealthCheck" Version="$(GrpcDotNetPackageVersion)" />
    <PackageVersion Include="Grpc.AspNetCore.HealthChecks" Version="$(GrpcDotNetPackageVersion)" />
    <PackageVersion Include="Grpc.Auth" Version="$(GrpcDotNetPackageVersion)" />
    <PackageVersion Include="Grpc.StatusProto" Version="$(GrpcDotNetPackageVersion)" />

    <!-- OpenTelemetry -->
    <PackageVersion Include="OpenTelemetry" Version="$(OpenTelemetryPackageVersion)" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="$(OpenTelemetryPackageVersion)" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="$(OpenTelemetryPackageVersion)" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="$(OpenTelemetryAspNetCoreInstrumentationPackageVersion)" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.GrpcNetClient" Version="$(OpenTelemetryGrpcPackageVersion)" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="$(OpenTelemetryHttpInstrumentationPackageVersion)" />

    <!-- Other -->
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageVersion Include="CommandLineParser" Version="2.9.1" />
    <PackageVersion Include="Google.Api.CommonProtos" Version="2.17.0" />
    <PackageVersion Include="Google.Apis.Auth" Version="1.75.0" />
    <PackageVersion Include="Google.Protobuf" Version="3.35.1" />
    <PackageVersion Include="Microsoft.Bcl.AsyncInterfaces" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Build.Locator" Version="1.11.2" />
    <PackageVersion Include="Microsoft.Build" Version="17.3.2" />
    <PackageVersion Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.400" />
    <PackageVersion Include="Microsoft.Crank.EventSources" Version="0.2.0-alpha.26316.1" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.400" />
    <PackageVersion Include="Microsoft.Win32.Registry" Version="5.0.0" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="Nunit" Version="4.3.2" />
    <PackageVersion Include="NUnit3TestAdapter" Version="6.2.0" />
    <PackageVersion Include="protobuf-net.Grpc.AspNetCore" Version="1.2.2" />
    <PackageVersion Include="protobuf-net.Grpc" Version="1.2.5" />
    <PackageVersion Include="System.CommandLine" Version="2.0.11" />
    <PackageVersion Include="System.Diagnostics.DiagnosticSource" Version="8.0.1" />
    <PackageVersion Include="System.Memory" Version="4.6.3" />
    <PackageVersion Include="System.Net.Http.WinHttpHandler" Version="8.0.3" />
    <PackageVersion Include="System.Security.Principal.Windows" Version="5.0.0" />
    <PackageVersion Include="System.Text.Json" Version="8.0.6" />
    <PackageVersion Include="System.Threading.Channels" Version="8.0.0" />
  </ItemGroup>
</Project>
