jobs:
  grpcAspNetCoreServer:
    source:
      repository: https://github.com/grpc/grpc-dotnet.git
      branchOrCommit: master
      project: perf/benchmarkapps/GrpcAspNetCoreServer/GrpcAspNetCoreServer.csproj
    readyStateText: Application started
    waitForExit: false
    variables:
      protocol: h2c
      enableCertAuth: false
      logLevel: None
    arguments: "--LogLevel {{logLevel}} --enableCertAuth {{enableCertAuth}} --protocol {{protocol}}"