jobs:
  grpcCoreServer:
    source:
      repository: https://github.com/grpc/grpc-dotnet.git
      branchOrCommit: master
      project: perf/benchmarkapps/GrpcCoreServer/GrpcCoreServer.csproj
    readyStateText: Application started
    waitForExit: false
    arguments: "--server.urls {{serverUri}}:{{serverPort}}"