name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]
  schedule:
    - cron: 0 0 * * * # daily at 00:00

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:

  build:
    name: Basic Tests
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v4
    
    - name: Install dotnet
      run: ./build/get-dotnet.sh

    - name: Build and run tests
      run: ./build_and_test.sh
  
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: artifacts
        path: artifacts
        if-no-files-found: error

  grpc_web:
    name: gRPC-Web Tests
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Run interop tests
      run: ./grpcweb_interoptests.sh
